#!/usr/bin/env bash
#
# Author sjdonado@uninorte.edu.co
# More info: https://aml-cs.github.io
#

wget -c https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_high_res_mandatory.tar.gz -P $WRF_ROOT_DIR/downloads

tar -zxvf $WRF_ROOT_DIR/downloads/geog_high_res_mandatory.tar.gz -C $WRF_ROOT_DIR/data
chmod -R 775 $WRF_ROOT_DIR/data/WPS_GEOG
