#!/bin/bash

if [[ -z $WPS_FORECASTS ]] || [[ -z $WPS_DIR ]] || [[ -z $WRF_DIR ]] || [[ -z $EC2_IP ]] || [[ -z $EC2_KEY ]]; then
    echo "Environment variables not set"
    exit 1
fi

FORECAST_START=18
PREFIX="/home/syseng/vdguevara/bin"

if [[ -n $1 ]]; then
    FORECAST_START=$1
fi

DATE_START=$(date "+%Y-%m-%d $FORECAST_START")
DATE_END=$(date --date="${DATE_START}+1day" '+%Y-%m-%d %H')

mkdir -p $HOME/forecasts
rm $HOME/forecasts/*

cd $WPS_FORECASTS
rm *
$PREFIX/download-forecast "$FORECAST_START"
$PREFIX/run-wps --from "${DATE_START}" --to "${DATE_END}" $WPS_FORECASTS
rm $HOME/forecasts/*
$PREFIX/run-wrf --from "${DATE_START}" --to "${DATE_END}" --time 24 --output "$HOME/forecasts/forecast"
