#!/usr/bin/env bash 
print_colored() {
    COLOR="\e[34m"
    NC="\e[39m"
    if [[ -n $2 ]]; then
        case $2 in
            red)
                COLOR="\e[31m"
                ;;
            green)
                COLOR="\e[32m"
                ;;
            blue)
                COLOR="\e[34m"
                ;;
            magenta)
                COLOR="\e[35m"
        esac
    fi

    if [[ -n $1 ]]; then
        echo -e "${COLOR}${1}${NC}"
    fi
}
