#!/usr/bin/env bash
#
# Author vdguevara@uninorte.edu.co
# More info: https://aml-cs.github.io
#

print_msg() {
    options=$(getopt -o c: --long color: -- "$@")
    [ $? -eq 0 ] || {
        echo "Incorrect option provided"
        exit 1
    }
    eval set -- "$options"

    COLOR="\e[39m"
    NC="\e[39m"
    while true; do
        case "$1" in
            -c|--color)
                shift
                case "$1" in
                    blue)
                        COLOR="\e[34m"
                        ;;
                    green)
                        COLOR="\e[32m"
                        ;;
                    magenta)
                        COLOR="\e[35m"
                        ;;
                    red)
                        COLOR="\e[31m"
                        ;;
                esac
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "Invalid option"
                exit 1
                ;;
        esac
        shift
    done
    echo -e "${COLOR}${1}${NC}"
}
