#!/usr/bin/env bash 

options=$(getopt -o d: --long directory: -- "$@")
eval set -- "$options"

while true; do
    case "$1" in
    -d|--directory)
        shift
        DIR=$(realpath $1)
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

for filename in $DIR/m*; do
    run-arwpost $filename "$DIR/ensemble-$(basename $filename)"
done
