#!/usr/bin/env bash
#
# Author sjdonado@uninorte.edu.co
# More info: https://aml-cs.github.io
#

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/print_msg"

options=$(getopt -o d:f:t: --long from: --long to: --long directory: -- "$@")
eval set -- "$options"

DIR=$(pwd)

while true; do
    case "$1" in
    -d|--directory)
        shift
        DIR=$(realpath $1)
        ;;
    -f|--from)
        shift
        FROM=$1
        ;;
    -t|--to)
        shift
        TO=$1
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

for filename in $DIR/m*; do
    print_msg "Reading ${filename}" -cmagenta
    run-arwpost -f "$FROM" -t "$TO" $filename "$DIR/ensemble-$(basename $filename)"
done
