#!/usr/bin/env bash 

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/print_msg"

options=$(getopt -o "WRw:r:o:f:t:s:h:i:" --long help --long only-wrf --long only-real --long wrf-processors:\
                                    --long real-processors: --long output: --long from: --long to:\
                                    --long time: --long interval: -- "$@")

function usage() {
    echo "Usage: $0 [options]"
    echo "Runs a WRF simulation using wrf.exe and real.exe"
    printf "\n  %-35s %s\n" "-W --only-wrf" "Run only wrf.exe"
    printf "  %-35s %s\n" "-R --only-real" "Run only real.exe"
    printf "  %-35s %s\n" "-w --wrf-processors=PROCESSORS" "How many processors to run wrf.exe with. The default value is 32"
    printf "  %-35s %s\n" "-r --real-processors=PROCESSOSRS" "How many processors to run real.exe with. The default value is 15"
    printf "  %-35s %s\n" "-f --from=DATE" "Start date"
    printf "  %-35s %s\n" "-t --to=DATE" "End date"
    printf "  %-35s %s\n" "-h --hours=HOURS" "Simulation time in hours"
    printf "  %-35s %s\n" "-i --interval=HOURS" "Simulation interval_seconds in hours"
    printf "  %-35s %s\n" "-o --output=DESTINATION" "Copy the output to DESTINATION"
    printf "  %-35s %s\n\n" "--help" "Show this message and exit"
    exit 0
}

eval set -- "$options"

DIR=$(pwd)
REAL=true
WRF=true
WRF_PROCESSORS=32
REAL_PROCESSORS=5
DESTINATION=${HOME}/wrf/output

while true; do
    case "$1" in
        -W|--only-wrf)
            REAL=false
            ;;

        -R|--only-real)
            WRF=false
            ;;

        -w|--wrf-processors)
            shift
            WRF_PROCESSORS="$1"
            ;;

        -r|--real-processors)
            shift
            REAL_PROCESSORS="$1"
            ;;

        -o|--output)
            shift
            DESTINATION=$(realpath $1)
            ;;

        --help)
            usage
            ;;

        -t|--to)
            shift
            TO=$1
            ;;

        -h|--hours)
            shift
            TIME=$1
            ;;
    
        -i|--interval)
            shift
            SECONDS=$(($1*3600))
            ;;

        -f|--from)
            shift
            FROM=$1
            ;;

        --)
            shift
            break
            ;;
    esac
    shift
done

cd ${WRF_DIR}/run

# Namelist modification

if [[ -n $TIME ]]; then
    sed -i "s/run_hours.*/run_hours = ${TIME},/" namelist.input
    print_msg "Run hours: ${TIME}" -cmagenta
fi

if [[ -n $SECONDS ]]; then
    sed -i "s/interval_seconds.*/interval_seconds = ${SECONDS},/" namelist.input
    print_msg "Inverval seconds: ${SECONDS}" -cmagenta
fi

if [[ -n $FROM ]]; then
    YEAR=$(date --date="${FROM}" +%Y)
    MONTH=$(date --date="${FROM}" +%m)
    DAY=$(date --date="${FROM}" +%d)
    HOUR=$(date --date="${FROM}" +%H)
    sed -i "s/start_year.*/start_year = $YEAR,$YEAR,$YEAR,/" namelist.input
    sed -i "s/start_month.*/start_month = $MONTH,$MONTH,$MONTH,/" namelist.input
    sed -i "s/start_day.*/start_day = $DAY,$DAY,$DAY,/" namelist.input
    sed -i "s/start_hour.*/start_hour = $HOUR,$HOUR,$HOUR,/" namelist.input
    print_msg "Start date: ${FROM}" -cmagenta
fi

if [[ -n $TO ]]; then
    YEAR=$(date --date="${TO}" +%Y)
    MONTH=$(date --date="${TO}" +%m)
    DAY=$(date --date="${TO}" +%d)
    HOUR=$(date --date="${TO}" +%H)
    sed -i "s/end_year.*/end_year = $YEAR,$YEAR,$YEAR,/" namelist.input
    sed -i "s/end_month.*/end_month = $MONTH,$MONTH,$MONTH,/" namelist.input
    sed -i "s/end_day.*/end_day = $DAY,$DAY,$DAY,/" namelist.input
    sed -i "s/end_hour.*/end_hour = $HOUR,$HOUR,$HOUR,/" namelist.input
    print_msg "End date: ${TO}" -cmagenta
fi

rm -f rsl.*
rm -f met_em*
ln -sf ${WPS_DIR}/met_em* .

if ${REAL}
then
    rm -f wrfinput_d* 2> /dev/null
    rm -f wrfbdy_d* 2> /dev/null 
    print_msg "Running real.exe with ${REAL_PROCESSORS} processors"
    # time sbatch run-real-sbatch
    time mpirun -np ${REAL_PROCESSORS} ./real.exe > stdout.log 2>&1
fi

if ${WRF}
then
    rm -rf ${WRF_DIR}/run/wrfout* 2> /dev/null
    print_msg "\nRunning wrf.exe with ${WRF_PROCESSORS} processors"
    # time sbatch run-wrf-sbatch
    time mpirun -np ${WRF_PROCESSORS} ./wrf.exe > stdout.log 2>&1
    if [ ! -f wrfout* ]; then
        cat rsl.error.0000
        exit 1
    fi
    chmod 777 wrfout* 2> /dev/null
    #cd ${DIR}
    cp ${WRF_DIR}/run/wrfout* ${DESTINATION}
    grep "SUCCESS COMPLETE WRF" "rsl.error.0000" > /dev/null
    if [[ $? -eq 0 ]]; then
        print_msg "Successful WRF run" -cgreen
    else
        print_msg "An error ocurred while running WRF" -cred
        exit 1
    fi
fi
