#!/bin/bash
#SBATCH --job-name=wrf-real           
#SBATCH --nodes=4              
#SBATCH --ntasks=5           
#SBATCH --cpus-per-task=1    
#SBATCH --time=24:00:00          
#SBATCH --account=syseng
#SBATCH --partition=syseng

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

echo "working directory = "$SLURM_SUBMIT_DIR

module purge
module load wrf/4.2.0

export WRFDA_ROOT=/opt/ohpc/pub/WRFDA-4DVAR
export WRFDA_DIR=/opt/ohpc/pub/WRFDA-4DVAR/work_dir
export OBSPROC_DIR=/opt/ohpc/pub/WRFDA-4DVAR/model/WRFDA/var/obsproc

mpiexec -n 5 ./real.exe