#!/bin/bash
#SBATCH --job-name=wrf           
#SBATCH --nodes=4                
#SBATCH --ntasks=32              
#SBATCH --cpus-per-task=1  
#SBATCH --time=24:00:00          
#SBATCH --account=syseng
#SBATCH --partition=syseng

module purge
module load wrf/4.2.0

mpiexec -n 32 ./wrf.exe